imzam/urls.py
from django.contrib import admin
from django.urls import include, path
from inventory.views import ParentLocationAutocompleteView

urlpatterns = [
    path("admin/parent_location_autocomplete", ParentLocationAutocompleteView.as_view(), name="parent_location_autocomplete"),
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path("", include("inventory.urls")),

]

inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    path("", views.index, name="index"),
	path(
        "loc/<int:pk>",
        views.DetailLocationView.as_view(),
        name="view_location2",
    ),
	path(
        "loc/move/<int:pk>",
        views.LocationMoveView.as_view(),
        name="location_move",
    ),
    path(
        "loc/<int:pk>/<str:unique_identifier>",
        views.DetailLocationView.as_view(),
        name="view_location",
    ),
    path(
        "loc/<int:pk>/<str:unique_identifier>/update",
        views.update_location,
        name="update_location",
    ),
    path("loc/", views.SearchableLocationListView.as_view(), name="index_locations"),
    path("item/create", views.CreateItemView.as_view(), name="create_item"),
    path("item/", views.SearchableItemListView.as_view(), name="index_items"),
    path("item/<int:pk>", views.DetailItemView.as_view(), name="view_item"),
    path("item/<int:pk>/annotate", views.AnnotateItemView.as_view(), name="annotate_item"),
    #path("item/<int:pk>/delete", views.DeleteItemView.as_view(), name="delete_item"),
    #path('item/<int:pk>/move', views.move_item, name='move_item'),
    #path('item/<int:pk>/take', views.takee_item, name='take_item'),
    path("item/<int:pk>/update", views.UpdateItemView.as_view(), name="update_item"),
    path("category/<int:pk>.json", views.category_json, name="category_json"),
    path("parent_location_autocomplete", views.ParentLocationAutocompleteView.as_view(), name="parent_location_autocomplete"),

    path("robots.txt", TemplateView.as_view(template_name="inventory/robots.txt", content_type="text/plain")),
    path('location-autocomplete/', views.LocationAutocomplete.as_view(), name='location-autocomplete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from datetime import datetime
from string import Template
import urllib.parse

from inventory.ocr_util import ocr_on_image_path
from paho.mqtt import client as mqttc
from pydoc import describe
from typing_extensions import Required
from xml.etree.ElementTree import Comment
from django.db import models
from django.core import validators
from computedfields.models import ComputedFieldsModel, computed
from django.forms import ValidationError
from django.urls import reverse
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.utils.timezone import make_aware
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from sorl.thumbnail import delete


# Create your models here.


class Item(models.Model):
    class Meta:
        verbose_name = _("item")
        verbose_name_plural = _("items")
        ordering = ["id"]

    # TODO use UUID as id?
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(_("item name"), max_length=512, blank=True, null=True)
    description = models.TextField(_("description"), blank=True)
    # TODO implement signal for automatic adoption by parent_location
    # https://stackoverflow.com/questions/43857902/django-set-foreign-key-to-parent_location-value-on-delete
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("category"),
    )
    measurement_unit = models.ForeignKey(
        "MeasurementUnit",
        on_delete=models.PROTECT,
        default=1,
        verbose_name=_("measurement unit"),
    )
    sale_price = models.DecimalField(
        _("sale price per unit"),
        max_digits=8,
        decimal_places=2,
        blank=True,
        null=True,
        default=None,
    )

    def __str__(self):
        if self.name:
            return self.name
        else:
            return _("Unnamed item") + f" {self.pk}"

    def get_absolute_url(self):
        return reverse("view_item", kwargs={"pk": self.pk})

    def get_admin_url(self):
        return reverse(
            "admin:inventory_item_change",
            args=(self.pk,),
        )
    
    @classmethod
    def filter_incomplete(cls, ordered=False):
        # prefilter:
        # only with image(s)
        relevant_items = cls.objects.filter(itemimage__isnull=False, itemlocation__isnull=False)

        # filter with complete information
        relevant_items = relevant_items.exclude(name__isnull=False, sale_price__isnull=False)

        if ordered:
            # prioritize items with price label image
            relevant_items = relevant_items.annotate(
                pl_count=models.Count('itemimage', filter=models.Q(itemimage__description="Price label")))

            # sorted by price label count and amount:
            relevant_items = relevant_items.annotate(
                amount=models.Sum(models.functions.math.Abs('itemlocation__amount')))
            relevant_items = relevant_items.order_by('-pl_count', '-amount')
        
        return relevant_items


class Category(ComputedFieldsModel):
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")
        ordering = ("full_name",)

    name = models.CharField(_("category name"), max_length=512)
    description = models.TextField(blank=True)
    # TODO implement signal for automatic adoption by parent_location
    # https://stackoverflow.com/questions/43857902/django-set-foreign-key-to-parent_location-value-on-delete
    parent_category = models.ForeignKey(
        "self",
        verbose_name=_("parent category"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    @computed(
        models.CharField(_("full name"), max_length=1024),
        depends=[("self", ["name"]), ("parent_category", ["full_name"])],
    )
    def full_name(self):
        if self.parent_category:
            return self.parent_category.full_name + "/" + self.name
        return self.name

    def __str__(self):
        return self.full_name


def get_item_upload_path(instance, filename):
    return f"items/{instance.item.id}/{datetime.now().isoformat()}_{filename}"


class ItemImage(models.Model):
    image = models.ImageField(_("image"), upload_to=get_item_upload_path)
    description = models.CharField(_("description"), max_length=512, blank=True)
    item = models.ForeignKey("Item", on_delete=models.CASCADE, verbose_name=_("item"))
    ocr_text = models.TextField(_("ocr text"), blank=True, null=True, editable=False)
    ocr_timestamp = models.DateTimeField(blank=True, null=True)

    def image_tag(self, location=None):
        return mark_safe(
            '<img src="%s" width="512" />' % escape(self.image.url)
        )
    image_tag.short_description = "Image"
    image_tag.allow_tags = True

    def update_ocr_text(self, ocr_text):
        self.ocr_text = ocr_text
        self.ocr_timestamp = make_aware(datetime.utcnow())
        self.save()

    def run_ocr(self):
        ocr_text = ocr_on_image_path(self.image.path)
        self.update_ocr_text(ocr_text)
        return ocr_text


@receiver(pre_delete, sender=ItemImage)
def delete_image(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    if instance.image:
        delete(instance.image, delete_file=False)  # delete thumbnails
        instance.image.delete(False)


class ItemFile(models.Model):
    file = models.FileField(_("file"), upload_to=get_item_upload_path)
    description = models.CharField(_("description"), max_length=512, blank=True)
    item = models.ForeignKey("Item", on_delete=models.CASCADE, verbose_name=_("file"))


@receiver(pre_delete, sender=ItemImage)
def delete_image(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    if instance.image:
        instance.image.delete(False)


class ItemBarcode(models.Model):
    # Enable after inital data cleanup:
    # class Meta:
    #     unique_together = [['data', 'type']]

    data = models.TextField(_("data"))
    type = models.ForeignKey(
        "BarcodeType",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("type"),
    )
    item = models.ForeignKey("Item", on_delete=models.CASCADE, verbose_name=_("Item"))

    def __str__(self):
        return f"{repr(self.data)} ({self.type})"


class BarcodeType(models.Model):
    class Meta:
        verbose_name = _("barcode type")
        verbose_name_plural = _("barcode types")

    name = models.CharField(_("name"), max_length=128, unique=True)

    def __str__(self):
        return self.name


class MeasurementUnit(models.Model):
    class Meta:
        verbose_name = _("measurement unit")
        verbose_name_plural = _("measurement units")

    name = models.CharField(_("name"), max_length=128, unique=True)
    short = models.CharField(_("abbreviation"), max_length=8, unique=True)
    description = models.TextField(_("description"), blank=True)

    def __str__(self):
        return f"{self.name} ({self.short})"


class LocationType(models.Model):
    class Meta:
        verbose_name = _("location type")
        verbose_name_plural = _("location types")

    name = models.CharField(_("name"), max_length=64, unique=True)
    # set if this Locations can not have sublocations (you can not put a box in a box)
    no_sublocations = models.BooleanField(_("no sublocations flag"), default=False)
    # allow this type to be moved from frontend
    moveable = models.BooleanField(_("moveable flag"), default=False)
    # set if Location.short is to be globally unique
    unique = models.BooleanField(_("unique flag"), default=False)
    # for automatic generation of unique names and short_names:
    auto_name_prefix = models.CharField(
        _("name prefix"), max_length=16, default="", blank=True
    )
    auto_short_name_prefix = models.CharField(
        _("short name prefix"), max_length=4, default="", blank=True
    )
    auto_short_name_padding_length = models.IntegerField(
        _("short name pedding"), default=0
    )
    auto_sequence = models.CharField(
        _("sequence"),
        max_length=128,
        choices=[
            ("0123456789", "Numeric (0-9)"),
            ("abcdefghijklmnopqrstuvwxyz", "Letters lowercase (a-z)"),
            ("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "Letters lowercase (a-z)"),
            (
                "0123456789abcdefghijklmnopqrstuvwxyz",
                "Alphanumeric lowercase (0-9, a-z)",
            ),
            ("0123456789abcdef", "Hexadecimal lowercase (0-9, a-f)"),
        ],
        null=True,
        blank=True,
    )

    default_label_template = models.ForeignKey(
        "LocationLabelTemplate",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=_("default label template"),
    )

    def int2str(self, i):
        seq = self.auto_sequence
        base = len(seq)
        s = ""
        remainder = int(i)
        while remainder > 0:
            s = seq[remainder % base] + s
            remainder = remainder // base
        if len(s) == 0:
            s = self.auto_sequence[0]
        return s

    def str2int(self, s):
        seq = self.auto_sequence
        base = len(seq)
        i = 0
        for p, c in enumerate(s[::-1]):
            i += base ** p * seq.index(c)
        return i

    def generate_names(self, count, start=None):
        if start is None:
            start = self.auto_sequence[0]

        names = []
        start_int = self.str2int(start)
        for i in range(start_int, start_int + count):
            index = self.int2str(i)
            index_padded = (
                max(0, (self.auto_short_name_padding_length - len(index)))
                * self.auto_sequence[0]
                + index
            )

inventory/templates/inventory/index.html
{% extends 'base.html' %}

{% load django_bootstrap5 i18n %}

{% block title %}
    {% trans "ZAM inv" %}
{% endblock %}

{% block content %}
Welcome to the ZAM Inventory Management System
{% endblock %}

inventory/templates/inventory/item_annotate_form.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load i18n %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}


{% block content %}
<div class="row">
<div class="col-lg">
<div id="carouselImageIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
    <div class="carousel-indicators">
      {% for img in object.itemimage_set.all %}
      <button type="button" data-bs-target="#carouselImageIndicators" data-bs-slide-to="{{ forloop.counter0 }}" class="active" aria-current="true" aria-label="{{ img.description }}"></button>
      {% endfor %}
    </div>
    <div class="carousel-inner">
      {% for img in object.itemimage_set.all %}
      <div class="carousel-item{% if forloop.first %} active{% endif %}">
        <img src="{{ img.image.url }}" class="d-block w-100" alt="{{ img.description }}">
      </div>
      {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselImageIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselImageIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
</div>
</div>

<div class="col-lg">
<table>
{% for il in object.itemlocation_set.all %}
    <tr>
        <td><a href="{{ il.location.get_absolute_url }}">{{ il.location }}</a></td>
        <td>{{ il.amount_text }}</td>
{% empty %}
    {% trans "Item is located nowhere." %}
{% endfor %}
</table>
<br/>
{% load crispy_forms_tags %}
{% crispy form %}
</div>
</div>

{% endblock %}

inventory/templates/inventory/item_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% trans "Delete Item" %}{% endblock %}

{% block content %}
<div class="alert alert-danger">
    <h4>{% trans "Are you sure you want to delete this item?" %}</h4>
    <p>{{ object.name }}</p>
</div>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
    <a href="{% url 'view_item' object.pk %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
</form>
{% endblock %}

inventory/templates/inventory/item_detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 i18n %}
{% load mytemplatetags %}
{% load thumbnail %}

{% block title %}
    {{ object.name }}
{% endblock %}

{% if form.instance.id %}
{% block admin_url %}
{{ object.get_admin_url }}
{% endblock %}
{% endif %}

{% block content %}
    <a href="{% url 'update_item' object.id %}">{% trans "edit" %}</a>
    <p>{{ object.description }}</p>

    {% for image in object.itemimage_set.all %}
    {% thumbnail image.image "200x200" as im %}
        {% spaceless %}
            <a class="img-link" href="{{ image.image.url }}">
                <img src="{{ im.url }}" class="img-thumbnail img-fluid" style="max-width: 200px;" alt="{{ image.description }}" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-original-title="{{ image.description }}">
            </a>
        {% endspaceless %}
    {% endthumbnail %}
{% endfor %}

    <h2>{% trans "Locations" %}</h2>
    <div>
    <table>
    {% for il in object.itemlocation_set.all %}
        <tr>
            <td><a href="{{ il.location.get_absolute_url }}">{{ il.location }}</a></td>
            <td>{{ il.amount_text }}</td>
            <td><a href="TODO">{% trans "Take" %}</a></td>
            <td><a href="TODO">{% trans "Move" %}</a></td>
    {% empty %}
        {% trans "Item is located nowhere." %}
    {% endfor %}
    </table>
    </div>
    
{% endblock %}

inventory/templates/inventory/item_list.html
{% extends 'base.html' %}

{% load django_bootstrap5 i18n %}
{% load mytemplatetags %}
{% load thumbnail %}
{% load static %}

{% block title %}
    {% trans "Item List" %}
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col'>
        <form method="get">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">🔎</span>
            <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="q" value="{{ request.GET.q }}">
        </div>
        </form>
    </div>
    {% if incomplete_count %}
        <div class='col-3'>
            <a href="{% url "annotate_item" incomplete_first_pk %}">Help annotate incomplete item descriptions ({{ incomplete_count }})</a>
        </div>
    {% endif %}
</div>
<div class="row mb-3">
    <div class="col">
        <a href="{% url 'create_item' %}" class="btn btn-primary">
            {% trans "Create New Item" %}
        </a>
    </div>
</div>
<table class="table table-striped">
    <thead><tr>
        <th scope="col">{% trans "Name" %}</td>
        <th scope="col">{% trans "Category" %}</td>
        <th scope="col">{% trans "Photos" %}</td>
        <th scope="col">{% trans "Locations" %}</td>
    </tr></thead>
    <tbody>
    {% for object in page_obj %}
        <tr>
        <th scope="row">
            <a href="{{ object.get_absolute_url }}">
            {{ object }}
            </a>
        </td>
        <td>
            {% if object.category %}
            <a href="{{ object.category.get_absolute_url }}">
            {{ object.category }}
            {% endif %}
            </a>
        </td>
        <td>
            {% for image in object.itemimage_set.all %}
                {% thumbnail image.image "200x200" as im %}
                    {% spaceless %}
                        <a class="img-link" href="{{ image.image.url }}">
                            <img src="{{ im.url }}" class="img-thumbnail img-fluid" style="max-width: 100px;" alt="{{ image.description }}" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-original-title="{{ image.description }}">
                        </a>
                    {% endspaceless %}
                {% endthumbnail %}
            {% endfor %}
        </td>
        <td>
            {% for itemloc in object.itemlocation_set.all %}
                <a href="{{ itemloc.location.get_absolute_url }}">
                {{ itemloc }}
                </a><br>
            {% endfor %}
        </a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% url_replace request 'page' 1 %}">&laquo; first</a>
            <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a>
            <a href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

{% block bootstrap5_extra_script %}
<script type="text/javascript" src="{% static 'inventory/simple-lightbox.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'inventory/simple-lightbox.min.css' %}" />
<script type="text/javascript">
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
})

new SimpleLightbox('a.img-link', { /* options */ });
</script>
{% endblock %}

inventory/templates/inventory/location_detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 i18n %}
{% load thumbnail %}

{% block item_nav %}
    {% if user.is_authenticated and object.type.moveable %}
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">{% trans "view" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'location_move' pk=object.id %}">{% trans "move" %}</a>
            </li>
        </ul>
    {% endif %}
{% endblock %}

{% block title %}
    {% trans "Location" %}:  {{ object.unique_identifier }}
{% endblock %}

{% if form.instance.id %}
{% block admin_url %}
{{ object.get_admin_url }}
{% endblock %}
{% endif %}

{% block content %}
    <p>{{ object.name }} ({{ object.type.name }})</p>
    <p>{{ object.descriptive_identifier }}</p>
    <p>{{ object.description }}</p>
    {% if object.parent_location %}
        <p><a href="{{ object.parent_location.get_absolute_url }}">{{ object.parent_location }}</a></p>
    {% else %}
        <p>{% trans "root location (has no parent)" %}</p>
    {% endif %}
    
    {% if object.get_lablary_url %}
        <img height="150em" src="{{ object.get_lablary_url }}"/>
    {% endif %}

    <h2>{% trans "Sub-Locations" %}</h2>
    <ul>
    {% for subloc in object.children.all %}
        <li><a href="{{ subloc.get_absolute_url }}">{{ subloc.unique_identifier }} {{ subloc.name }}</a>
    {% empty %}
        {% trans "No sub-locations." %}
    {% endfor %}
    </ul>

    <h2>{% trans "Items" %}</h2>
    <div>
    <table>
    {% for il in object.itemlocation_set.all %}
        <tr>
            <td><a href="{{ il.item.get_absolute_url }}">{{ il.item }}</a></td>
            <td>{{ il.amount_text }}</td>
            <td>
                {% for image in il.item.itemimage_set.all %}
                    {% thumbnail image.image "200x200" as im %}
                        {% spaceless %}
                            <a class="img-link" href="{{ image.image.url }}">
                                <img src="{{ im.url }}" class="img-thumbnail img-fluid" style="max-width: 100px;" alt="{{ image.description }}" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-original-title="{{ image.description }}">
                            </a>
                        {% endspaceless %}
                    {% endthumbnail %}
                {% endfor %}
            </td>
            <!--<td><a href="TODO">{% trans "Take" %}</a></td>
            <td><a href="TODO">{% trans "Move" %}</a></td>-->
    {% empty %}
        {% trans "No items located here." %}
    {% endfor %}
    </table>
    {% trans "Items at sub-locations are not included!" %}
    </div>
    
    <p><a href="{% url 'create_item' %}?location_id={{ object.pk }}">{% trans "Add item..." %}</a></p>
{% endblock %}

inventory/templates/inventory/location_list.html
{% extends 'base.html' %}

{% load mytemplatetags %}
{% load django_bootstrap5 i18n %}
{% load bootstrap_icons %}

{% block title %}
    {% trans "Location List" %}
{% endblock %}

{% block content %}
<form method="get">
<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">🔎</span>
    <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="q" value="{{ request.GET.q }}">
</div>
</form>
<table class="table table-striped">
    <thead><tr>
        <th scope="col">
            {% trans "Identifier" %}
            {% if sort_helper.is_sorted_by_unique_identifier == "asc" %}
            <a href="{{ request.path }}{{ sort_helper.get_sort_query_by_unique_identifier_desc }}">
            {% bs_icon 'sort-up' color="red" %}
            </a>
            {% elif sort_helper.is_sorted_by_unique_identifier == "desc" %}
            <a href="{{ request.path }}{{ sort_helper.get_sort_query_by_unique_identifier_asc }}">
            {% bs_icon 'sort-down' color="red" %}
            </a>
            {% else %}
            <a href="{{ request.path }}{{ sort_helper.get_sort_query_by_unique_identifier_desc }}">
            {% bs_icon 'sort-down' %}
            </a>
            {% endif %}
        </th>
        <th scope="col">{% trans "Name" %}</th>
        <th scope="col">{% trans "Items" %}</th>
    </tr></thead>
    <tbody>
    {% for object in page_obj %}
        <tr>
        <td scope="row">
            <a href="{{ object.get_absolute_url }}" data-bs-toggle="tooltip" title="" data-bs-original-title="{{ object.descriptive_identifier }}">
                {{ object.unique_identifier }}
            </a>
        </td>
        <td>
            <a href="{{ object.get_absolute_url }}" data-bs-toggle="tooltip" title="" data-bs-original-title="{{ object.descriptive_identifier }}">
                {{ object.name }}
            </a>
        </td>
        <td>
            {{ object.itemlocation_set.count }}
        </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?{% url_replace request 'page' 1 %}">&laquo; first</a>
            <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a>
            <a href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

{% block bootstrap5_extra_head %}
<script type="text/javascript">
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
})
</script>
{% endblock %}

inventory/templates/inventory/location_move.html
{% extends 'base.html' %}

{% load static %}

{% load django_bootstrap5 i18n %}

{% block item_nav %}
    {% if user.is_authenticated %}
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'view_location2' pk=object.id %}">{% trans "view" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">{% trans "move" %}</a>
            </li>
        </ul>
    {% endif %}
{% endblock %}

{% block title %}
    {% trans "Move Location" %}:  {{ object.unique_identifier }}
{% endblock %}

{% if form.instance.id %}
{% block admin_url %}
{{ object.get_admin_url }}
{% endblock %}
{% endif %}

{% block content %}
    <p>{{ object.name }} ({{ object.type.name }})</p>
    <p>{% trans "Current Parent Location" %}: {{ object.parent_location.descriptive_identifier }}</p>
    <p>{{ object.description }}</p>
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}

        <table>
            {{ view.formset }}
        </table>
        <input type="submit" value="{% trans "Save" %}" />
    </form>

{% endblock %}

{% block bootstrap5_extra_head %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block bootstrap5_extra_script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'static_jquery/js/jquery.min.js' %}"></script>
{{ form.media }}
{% endblock %}